[phases.build]
cmds = ["composer install --no-dev", "npm install", "npm run build", "php artisan config:clear", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"]

[phases.setup]
nixPkgs = ["...", "php82", "php82Packages.composer", "nodejs"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
